blog/urls.py
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .feeds import RSSSiteNewsFeed, AtomSiteNewsFeed


app_name = "blog"

urlpatterns = [
    url(r'^$', views.list_of_post, name='list_of_post'),
    # url(r'^$', TemplateView.as_view(template_name='blog/list_of_post.html'), name='list_of_post'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name='list_of_post_by_category'),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^rss/feed/$', RSSSiteNewsFeed()),
    url(r'^sitenews/atom/$', AtomSiteNewsFeed()),
]

# TODO haystack search

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

representlaw/urls.py
# from django.urls import include, path
from representlaw import views as representlaw_views


from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [

    url(r'^', include('website.urls', namespace='website')),
    url(r'^admin/', admin.site.urls),
    url(r'^myaccount/', include('myaccount.urls', namespace='myaccount')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^contact/$', ContactView.as_view(), name='envelope-contact'),
    # url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^website/', include('website.urls', namespace='website')),
]

website/urls.py
from django.conf.urls import url, include
from website.views import HomeView
from django.views.generic import TemplateView

app_name = "website"

urlpatterns = [
    # url(r'^$', HomeView.as_view(), name='home'),
    url(r'^$', TemplateView.as_view(template_name='website/home_temp.html'), name='home_temp'),
    url(r'^about/$', TemplateView.as_view(template_name='website/about.html'), name='about'),
    url(r'^terms-and-conditions/$', TemplateView.as_view(template_name='website/terms-and-conditions.html'),
        name='terms_and_conditions'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='website/privacy-policy.html'), name='privacy-policy'),

    # url(r'^contact/$', TemplateView.as_view(template_name='website/contact.html'), name='contact'),

    # url(r'^contact/', include('contact_form.urls'), name='contact_form'),
    # url(r'^contact/',    include('envelope.urls'), name='contact_form'),

    url(r'^cookie-policy/$', TemplateView.as_view(template_name='website/cookie-policy.html'),
        name='cookie-policy'),

    # Conveyancing Commercial
    url(r'^conveyancing-commercial/$',
        TemplateView.as_view(template_name='website/conveyancing-commercial/conveyancing-commercial-home.html'),
        name='conveyancing-commercial-home'),

    # Conveyancing Residential
    url(r'^conveyancing-residential/$',
        TemplateView.as_view(template_name='website/conveyancing-residential/conveyancing-residential-home.html'),
        name='conveyancing-residential-home'),

    # Elderly Client
    url(r'^elderly-client-services/$',
        TemplateView.as_view(template_name='website/elderly-client/elderly-client-home.html'),
        name='elderly-client-home'),

    # Employment
    url(r'^employment-and-tribunals/$',
        TemplateView.as_view(template_name='website/employment/employment-home.html'),
        name='employment-home'),

    # Family
    url(r'^family-and-children/$',
        TemplateView.as_view(template_name='website/family-and-children/family-home.html'),
        name='family-home'),


    # Leasehold
    url(r'^leasehold/$', TemplateView.as_view(template_name='website/leasehold/testing.html'), name='leasehold-home'),

    url(r'^leasehold/what_is_leasehold$',
        TemplateView.as_view(template_name='website/leasehold/what_is_leasehold.html'),
        name='leasehold-what_is_leasehold'),

    # Litigation
    url(r'^litigation-and-disputes/$',
        TemplateView.as_view(template_name='website/litigation-and-disputes/litigation-home.html'),
        name='litigation-home'),

    # Power Attorney
    url(r'^power-attorney-court-protection/$',
        TemplateView.as_view(template_name='website/power-attorney-court-protection/power-attorney-court-protection.html'),
        name='power-attorney-home'),

    # Probate and Estate services
    url(r'^probate-and-estates/$', TemplateView.as_view(template_name='website/probate-and-estates/probate-home.html'),
        name='probate-home'),


    # Renters
    url(r'^renting/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renting-home'),
    url(r'^renting/faqs$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'),
        name='renting-faqs-english'),

    # Will writing services
    url(r'^wills/$', TemplateView.as_view(template_name='website/wills/will-writing.html'), name='wills'),
    url(r'^wills-trusts/$', TemplateView.as_view(template_name='website/wills/wills-trusts.html'), name='wills-trusts'),
    url(r'^wills/make-my-will$', TemplateView.as_view(template_name='website/wills/make-my-will.html'),
        name='make-my-will'),


    # Renting
    url(r'^renters/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renters-home'),
    url(r'^renters/renting-faqs/$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'), name='renters-faqs'),


    # Renting/deposits

    url(r'^renters/assured-shorthold-tenancies$',
        TemplateView.as_view(template_name='website/renters/assured-shorthold-tenancies.html'),
        name='renters-assured-shorthold-tenancies'),

    url(r'^renters/assured_tenancies$',
        TemplateView.as_view(template_name='website/renters/assured_tenancies.html'),
        name='renters-assured_tenancies'),

    url(r'^renters/can_council_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_council_tenants_stop_the_bailiffs.html'),
        name='renters-can_council_tenants_stop_the_bailiffs'),

    url(r'^renters/can_housing_association_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_housing_association_tenants_stop_the_bailiffs.html'),
        name='renters-can_housing_association_tenants_stop_the_bailiffs'),

    url(r'^renters/can_private_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_private_tenants_stop_the_bailiffs.html'),
        name='renters-can_private_tenants_stop_the_bailiffs'),

    url(r'^renters/complain_to_environmental_health_about_rented_housing$',
        TemplateView.as_view(template_name='website/renters/complain_to_environmental_health_about_rented_housing.html'),
        name='renters-complain_to_environmental_health_about_rented_housing'),

    url(r'^renters/complain_about_council_or_housing_association_repairs$',
        TemplateView.as_view(
            template_name='website/renters/complain_about_council_or_housing_association_repairs.html'),
        name='renters-complain_about_council_or_housing_association_repairs'),

    url(r'^renters/complain_to_the_ombudsman_about_repairs_in_social_housing$',
        TemplateView.as_view(
            template_name='website/renters/complain_to_the_ombudsman_about_repairs_in_social_housing.html'),
        name='renters-complain_to_the_ombudsman_about_repairs_in_social_housing'),

    url(r'^renters/damage_or_wear_and_tear$',
        TemplateView.as_view(
            template_name='website/renters/damage_or_wear_and_tear.html'),
        name='renters-damage_or_wear_and_tear'),

    url(r'^renters/damp_and_mould_in_rented_homes$',
        TemplateView.as_view(
            template_name='website/renters/damp_and_mould_in_rented_homes.html'),
        name='renters-damp_and_mould_in_rented_homes'),

    url(r'^renters/deposit-check$', TemplateView.as_view(template_name='website/renters/deposit-check.html'),
        name='renters-deposit-check'),

    url(r'^renters/deposit-check-lookup$',
        TemplateView.as_view(
            template_name='website/renters/deposit-check-lookup.html'),
        name='renters-deposit-check-lookup'),

    url(r'^renters/disrepair-advice$',
        TemplateView.as_view(template_name='website/renters/disrepair-advice.html'),
        name='renters-disrepair-advice'),

    url(r'^renters/doing_the_repairs_if_your_landlord_wont$',
        TemplateView.as_view(
            template_name='website/renters/doing_the_repairs_if_your_landlord_wont.html'),
        name='renters-doing_the_repairs_if_your_landlord_wont'),

    url(r'^renters/deposit-protection-claims$',
        TemplateView.as_view(template_name='website/renters/deposit-protection-claims.html'),
        name='deposit-protection-claims'),

    url(r'^renters/electrical_safety_in_rented_homes$',
        TemplateView.as_view(template_name='website/renters/electrical_safety_in_rented_homes.html'),
        name='renters-electrical_safety_in_rented_homes'),

    url(r'^renters/ending_a_periodic_tenancy$',
        TemplateView.as_view(template_name='website/renters/ending_a_periodic_tenancy.html'),
        name='renters-ending_a_periodic_tenancy'),

    url(r'^renters/energy_costs_in_shared_accommodation$',
        TemplateView.as_view(template_name='website/renters/energy_costs_in_shared_accommodation.html'),
        name='renters-energy_costs_in_shared_accommodation'),

    url(r'^renters/eviction$',
        TemplateView.as_view(template_name='website/renters/eviction.html'),
        name='renters-eviction'),

    url(r'^renters/eviction_documents_the_court_sends_you$',
        TemplateView.as_view(template_name='website/renters/eviction_documents_the_court_sends_you.html'),
        name='renters-eviction_documents_the_court_sends_you'),

    url(r'^renters/eviction_for_rent_arrears$',
        TemplateView.as_view(template_name='website/renters/eviction_for_rent_arrears.html'),
        name='renters-eviction_for_rent_arrears'),

    url(r'^renters/eviction-of-assured-shorthold-tenants$',
        TemplateView.as_view(template_name='website/renters/eviction-of-assured-shorthold-tenants.html'),
        name='renters-eviction-of-assured-shorthold-tenants'),

    url(r'^renters/eviction_of_assured_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_assured_tenants.html'),
        name='renters-eviction_of_assured_tenants'),

    url(r'^renters/eviction_of_lodgers_and_other_excluded_occupiers$',
        TemplateView.as_view(template_name='website/renters/eviction_of_lodgers_and_other_excluded_occupiers.html'),
        name='renters-eviction_of_lodgers_and_other_excluded_occupiers'),

    url(r'^renters/eviction_of_regulated_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_regulated_tenants.html'),
        name='renters-eviction_of_regulated_tenants'),

    url(r'^renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection$',
        TemplateView.as_view(template_name='website/renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection.html'),
        name='renters-eviction_of_students_in_halls_and_other_occupiers_with_basic_protection'),

    url(r'^renters/eviction_notices_from_private_landlords',
        TemplateView.as_view(template_name='website/renters/eviction_notices_from_private_landlords.html'),
        name='renters-eviction_notices_from_private_landlords'),

website/models.py
from django.db import models

# Create your models here.

# Test
class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()

    def __str__(self):
        return self.name
# End Test

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class NewsletterUserSignUpForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels=False

    class Meta:
        model = NewsletterUserSignUpFormfield = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email


# Test

# from invoices.models import Customer
class InvoiceForm(forms.Form):
    FORMAT_CHOICES = (
        ('pdf', 'PDF'),
        ('docx', 'MS Word'),
        ('html', 'HTML'),
    )
    number = forms.CharField(label='Invoice #')
    # customer = forms.ModelChoiceField(queryset=Customer.objects.all())
    subject = forms.CharField()
    amount = forms.DecimalField()
    format = forms.ChoiceField(choices=FORMAT_CHOICES)

# End Test

website/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from blog.models import Post
# from docx import *
from docx import Document
# from docx.shared import Inches
from django.http import HttpResponse
import datetime
from io import StringIO


class HomeView(TemplateView):
    template_name = 'website/home.html'


def home(request, template_name):
    return render(request, template_name)


def latest_post_footer(request):
    post = Post.objects.order_by('-published')[0:3]
    template = 'website/base.html'
    context = {'posts': post}
    return render(request, template, context)

# Test
from reportlab.pdfgen import canvas
from django.http import HttpResponse


def some_view(request):
    if request.GET.get('pdf'):
        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

        # Create the PDF object, using the response object as its "file."
        p = canvas.Canvas(response)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response

# End Test

'''
def test_document(request):

    document = Document()
    docx_title = "TEST_DOCUMENT.docx"
    # ---- Cover Letter ----
    # document.add_picture((r'%s/static/images/my-header.png' % (settings.PROJECT_PATH)), width=Inches(4))
    document.add_paragraph()
    document.add_paragraph("%s" % datetime.date.today().strftime('%d, %B, %Y'))

    document.add_paragraph('Dear Sir or Madam:')
    document.add_paragraph('We are pleased to help you with your widgets.')
    document.add_paragraph('Please feel free to contact me for any additional information.')
    document.add_paragraph('I look forward to assisting you in this project.')

    document.add_paragraph()
    document.add_paragraph('Best regards,')
    document.add_paragraph('Acme Specialist 1]')
    document.add_page_break()

    # Prepare document for download
    # -----------------------------
    f = StringIO()
    document.save(f)
    length = f.tell()
    f.seek(0)
    response = HttpResponse(
        f.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    response['Content-Disposition'] = 'attachment; filename=' + docx_title
    response['Content-Length'] = length
    return response'''

website/templates/website/renters/deposit-check.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Represent Renters Deposit Protection Check{% endblock %}
{% block description %}Represent Renters Deposit Protection Check{% endblock %}
{% block author %}Represent{% endblock %}

{% block head %}
    <link href="{% static 'website/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
    <link rel="icon" type="image/jpg" sizes="32x32" href="/website/img/represent_icon2.jpg">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
{% endblock %}

{% block body %}

<!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron" style="background-color:black">
            <div class="container">

              <div class="bs-docs-header">
                <h1 style="color:white" align="center">Represent Renters</h1>
                <h1 align="center"><small style="color:white">Check if your deposit was protected</small></h1>
              </div>
            </div>
        </div>

<!--FAQs-->

<div class="container-fluid">
    <div class="col-md-6 offset-md-2">

        <div class="page-header">
            <h1 align="center">Check if your tenancy deposit is protected
            </h1>
        </div>

                <h1></h1>

        			<div class="data entry_content">
			<div class="inner_content">
				<section class="frame">
                    <iframe src="{% url 'website:renters-deposit-check-lookup' %}" height="500" width="700"></iframe>
				</section>
			</div>
		</div>


                    <p>There is no one way or central place to check if your landlord has protected your tenancy deposit.</p>
                    <p>The 3 tenancy deposit scheme providers each have a website you can use to check.&nbsp;</p>
                    <p>You'll have to supply your&nbsp;rental property postcode, tenancy start date, tenancy deposit amount and the&nbsp;tenant's name.</p>

                    <p class="inline-callout external">
                    <a href="https://www.thedisputeservice.co.uk/is-my-deposit-protected.html"
                       title="Link to The Dispute Service" target="_blank">Tenancy Deposit Scheme (TDS)</a></p>
                        <p><a href="https://www.depositprotection.com/is-my-deposit-protected"
                              title="Link to The Deposit Protection Service" target="_blank" class="inline-callout external">Deposit Protection Service (DPS)</a></p>
                        <p><a href="https://www.mydeposits.co.uk/tenants/deposit-checker/"
                              title="Link to mydeposits" target="_blank" class="inline-callout external">mydeposits</a></p>
                        <p>Tenancy&nbsp;deposits previously held by Capita Tenancy Deposit Service are now protected by&nbsp;mydeposits.</p>

                <h3>Who should check</h3>
                    <p>Only check&nbsp;if&nbsp;you have an&nbsp;
                        <a href="{% url 'website:renters-assured-shorthold-tenancies' %}" title="see also: assured shorthold tenancies">assured shorthold tenancy</a>.
                    </p>
                    <p>Landlords don't have to protect your tenancy deposit if
                        <a href="{% url 'website:renters-lodgers' %}"
                           title="see also: lodgers">you are a lodger</a>
                    or a
                        <a href="{% url 'website:renters-university_accommodation_halls_of_residence' %}"
                           title="see also: student halls of residence">student in halls</a>.</p>

                <h2>What to do next</h2>

                <p>Your landlord usually has 30 days from when you pay your deposit to:&nbsp;</p>

                <ul>
                    <li>protect your tenancy deposit with a government-backed scheme</li>
                    <li>tell you which scheme they've used</li>
                    <li>give you certain information about the scheme</li>
                </ul>
                    <p>If they don't, you can
                        <a href="{% url 'website:deposit-protection-claims' %}"
                           title="See also: tenancy deposit compensation claims">
                            take your landlord to court to claim tenancy deposit compensation</a>.
                    </p>
                    <p class="inline-highlight">Compensation can be between 1 and&nbsp;3 times
                        the amount of your deposit.</p>

                <div class="bs-callout bs-callout-primary">
                    <a href="{% url 'website:contact' %}"><h4>Claim compensation for not protecting your deposit</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation if your landlord hasn't protected your deposit.</p>
                    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>

                <h3>If your deposit isn't yet protected</h3>
                <p>Follow our 5 step guide:&nbsp;
                    <a href="{% url 'website:renters-get-deposit-protected' %}"
                       title="see also: how to protect your tenancy deposit ">
                        how to get a landlord to protect your tenancy deposit</a>.
                </p>


                <h3>If your deposit was protected late</h3><p>Find out how to take court action to&nbsp;
                <a href="{% url 'website:deposit-protection-claims' %}" title="See also: tenancy deposit compensation claims">
                    get your tenancy deposit protected or returned and claim compensation</a>.</p>

                <div class="bs-callout bs-callout-primary">
                    <a href="{% url 'website:contact' %}"><h4>Claim compensation for not protecting your deposit</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation if your landlord hasn't protected your deposit.</p>
                    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>

                <h3>If your tenancy deposit was protected in time</h3>
                <p>Find out
                    <a href="{% url 'website:renters-how-to-get-your-deposit-back' %}"
                       title="See also: how to get your tenancy deposit back at the end of your tenancy">
                        how to get your deposit back at the end of your tenancy</a>.
                </p>
                <p></p>
                <p>  </p>
            </div>




            </div>
        </div>
</div>




</div>





{% endblock %}

website/templates/website/renters/poor_conditions_in_council_or_housing_association_homes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Represent - Poor conditions in council or housing association homes{% endblock %}
{% block description %}If poor conditions in your home are putting your health at risk, report them to your landlord immediately.{% endblock %}
{% block author %}Represent{% endblock %}

{% block head %}
    <link href="{% static 'website/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
    <link rel="icon" type="image/jpg" sizes="32x32" href="/website/img/represent_icon2.jpg">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
{% endblock %}

{% block body %}

<!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron" style="background-color:black">
            <div class="container">

              <div class="bs-docs-header">
                <h1 style="color:white" align="center">Represent Renters</h1>
                <h1 align="center"><small style="color:white">Poor conditions in council or housing association homes</small></h1>
              </div>
            </div>
        </div>

<!--FAQs-->
<div class="container-fluid">
    <div class="col-md-6 offset-md-2">
        <div class="page-header">
            <h1>Poor conditions in council or housing association homes<br>
                <small>If poor conditions in your home are putting your health at risk, report them to your
                        landlord immediately.</small>
            </h1>
        </div>

    <h2>Conditions that can affect your health or safety</h2>
        <p>It's important to deal with problems in your home such as:</p>
        <ul type="disc">
            <li><a href="{% url 'website:renters-damp_and_mould_in_rented_homes' %}"
                               title="see also: damp and mould">damp, condensation, and mould</a></li>
            <li><a href="{% url 'website:renters-pests_and_vermin_infestations_in_rented_homes' %}"
                   title="see also: pests and vermin">rats, cockroaches and other infestations</a></li>
            <li><a href="{% url 'website:renters-gas_safety_in_rented_homes' %}"
                   title="see also: gas safety">gas safety</a>,
                <a href="{% url 'website:renters-electrical_safety_in_rented_homes' %}"
                   title="see also: electrical safety">electrical safety</a> and
                <a href="{% url 'website:renters-fire_safety_advice_for_tenants' %}"
                   title="see also: fire safety">fire safety</a> issues</li>
            <li>broken glass, falling plaster, or dangerous stairs</li>
            <li>blocked drains or problems with rubbish or sewage</li>
            <li>unacceptable noise levels</li>
            <li>damaged asbestos</li>
        </ul>

        <div class="bs-callout bs-callout-primary">
                    <a href="{% url 'website:contact' %}"><h4>Claim compensation for disrepair</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation for disrepair.</p>
                    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>

    <h2>Report poor conditions</h2>
        <p>You can report poor conditions in the same way as you
            <a href="{% url 'website:renters-how_to_report_repairs_to_a_social_landlord' %}"
               title="See also: reporting repairs">report repair problems</a>. Tell your landlord how your health or
            safety is affected.</p>
        <p>You must allow your landlord or their contractor access to see what the problem is and what can be done
            about it.&nbsp;Allow a reasonable time for the work to be done.</p>

        <div class="bs-callout bs-callout-primary">
                    <a href="{% url 'website:contact' %}"><h4>Claim compensation for disrepair</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation for disrepair.</p>
                    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>

    <h2>Complain to environmental health</h2>
        <p>You can contact the
            <a href="{% url 'website:renters-complain_to_environmental_health_about_rented_housing' %}"
               title="See also: Complain to environmental health">environmental health department</a> at your local council
            if the council or housing association landlord doesn't fix the problems,</p>
        <p>An environmental health officer should inspect your home.&nbsp;They use the
            <a href="{% url 'website:renters-health_and_safety_standards_for_rented_homes_hhsrs' %}"
               title="See also: Housing Health and Safety Rating System">Housing Health and Safety Rating System</a>
            to check if the conditions in your home are a risk to your health or safety.</p>

    <h3>Council tenants</h3>
        <p>Environmental health can't take formal enforcement action against the council, but it can:</p>
        <ul type="disc">
            <li>serve an informal notice telling your housing office to do repair work</li>
            <li>send them a report that sets out what needs to be done to make your home safe</li>
        </ul>
        <p>Use your council's complaints procedure if the housing office won't do the work that's needed or
            doesn't pay attention to the environment health report.</p>

    <h3>Housing association tenants</h3>
        <p>Environmental health can take enforcement action against the housing association. They may order
            them to&nbsp;take action to tackle the problems in your home.</p>
        <p>Use your housing association's complaints procedure if they won't do the work that's needed.</p>

        <div class="bs-callout bs-callout-primary">
                    <a href="{% url 'website:contact' %}"><h4>Claim compensation for disrepair</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation for disrepair.</p>
                    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>

   <h3>Problems affecting neighbours</h3>
        <p>The environmental health department may decide that the conditions in your home also cause a nuisance or
            risk to your neighbours or the public.</p>
        <p>These could include:</p>
        <ul type="disc">
            <li>tiles falling off your roof on to the street</li>
            <li>a toilet leaking into the flat downstairs</li>
        </ul>

   <h2>Complain to the Ombudsman</h2>
        <p>If making a complaint to your landlord isn't successful, consider
            <a href="{% url 'website:renters-complain_to_the_ombudsman_about_repairs_in_social_housing' %}"
               title="see also: complaining to the Ombudsman">complaining to the Ombudsman</a>. You may also be able to
            <a href="{% url 'website:renters-legal_action_if_your_landlord_wont_do_repairs' %}"
               title="See also: Court action for disrepair">take legal action against your landlord</a>.</p>

         <div class="bs-callout bs-callout-primary">
    <a href="{% url 'website:contact' %}"><h4>Do you have a renting problem?</h4></a>
    <p></p>
    <p>Get in touch with Represent to see how we can help</p>
    <p><a href="{% url 'website:contact' %}" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>
</div>



    </div>
</div>

{% endblock %}