blog/urls.py
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .feeds import RSSSiteNewsFeed, AtomSiteNewsFeed


app_name = "blog"

urlpatterns = [
    url(r'^$', views.list_of_post, name='list_of_post'),
    # url(r'^$', TemplateView.as_view(template_name='blog/list_of_post.html'), name='list_of_post'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name='list_of_post_by_category'),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^rss/feed/$', RSSSiteNewsFeed()),
    url(r'^sitenews/atom/$', AtomSiteNewsFeed()),
]

# TODO haystack search

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

representlaw/urls.py
# from django.urls import include, path
from representlaw import views as representlaw_views


from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [

    url(r'^', include('website.urls', namespace='website')),
    url(r'^admin/', admin.site.urls),
    url(r'^myaccount/', include('myaccount.urls', namespace='myaccount')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^contact/$', ContactView.as_view(), name='envelope-contact'),
    # url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^website/', include('website.urls', namespace='website')),
]

website/urls.py
from django.conf.urls import url, include
from website.views import HomeView
from django.views.generic import TemplateView

app_name = "website"

urlpatterns = [
    # url(r'^$', HomeView.as_view(), name='home'),
    url(r'^$', TemplateView.as_view(template_name='website/home_temp.html'), name='home_temp'),
    url(r'^about/$', TemplateView.as_view(template_name='website/about.html'), name='about'),
    url(r'^terms-and-conditions/$', TemplateView.as_view(template_name='website/terms-and-conditions.html'),
        name='terms_and_conditions'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='website/privacy-policy.html'), name='privacy-policy'),

    # url(r'^contact/$', TemplateView.as_view(template_name='website/contact.html'), name='contact'),

    # url(r'^contact/', include('contact_form.urls'), name='contact_form'),
    # url(r'^contact/',    include('envelope.urls'), name='contact_form'),

    url(r'^cookie-policy/$', TemplateView.as_view(template_name='website/cookie-policy.html'),
        name='cookie-policy'),

    # Conveyancing Commercial
    url(r'^conveyancing-commercial/$',
        TemplateView.as_view(template_name='website/conveyancing-commercial/conveyancing-commercial-home.html'),
        name='conveyancing-commercial-home'),

    # Conveyancing Residential
    url(r'^conveyancing-residential/$',
        TemplateView.as_view(template_name='website/conveyancing-residential/conveyancing-residential-home.html'),
        name='conveyancing-residential-home'),

    # Elderly Client
    url(r'^elderly-client-services/$',
        TemplateView.as_view(template_name='website/elderly-client/elderly-client-home.html'),
        name='elderly-client-home'),

    # Employment
    url(r'^employment-and-tribunals/$',
        TemplateView.as_view(template_name='website/employment/employment-home.html'),
        name='employment-home'),

    # Family
    url(r'^family-and-children/$',
        TemplateView.as_view(template_name='website/family-and-children/family-home.html'),
        name='family-home'),


    # Leasehold
    url(r'^leasehold/$', TemplateView.as_view(template_name='website/leasehold/testing.html'), name='leasehold-home'),

    url(r'^leasehold/what_is_leasehold$',
        TemplateView.as_view(template_name='website/leasehold/what_is_leasehold.html'),
        name='leasehold-what_is_leasehold'),

    # Litigation
    url(r'^litigation-and-disputes/$',
        TemplateView.as_view(template_name='website/litigation-and-disputes/litigation-home.html'),
        name='litigation-home'),

    # Power Attorney
    url(r'^power-attorney-court-protection/$',
        TemplateView.as_view(template_name='website/power-attorney-court-protection/power-attorney-court-protection.html'),
        name='power-attorney-home'),

    # Probate and Estate services
    url(r'^probate-and-estates/$', TemplateView.as_view(template_name='website/probate-and-estates/probate-home.html'),
        name='probate-home'),


    # Renters
    url(r'^renting/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renting-home'),
    url(r'^renting/faqs$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'),
        name='renting-faqs-english'),

    # Will writing services
    url(r'^wills/$', TemplateView.as_view(template_name='website/wills/will-writing.html'), name='wills'),
    url(r'^wills-trusts/$', TemplateView.as_view(template_name='website/wills/wills-trusts.html'), name='wills-trusts'),
    url(r'^wills/make-my-will$', TemplateView.as_view(template_name='website/wills/make-my-will.html'),
        name='make-my-will'),


    # Renting
    url(r'^renters/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renters-home'),
    url(r'^renters/renting-faqs/$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'), name='renters-faqs'),


    # Renting/deposits

    url(r'^renters/assured-shorthold-tenancies$',
        TemplateView.as_view(template_name='website/renters/assured-shorthold-tenancies.html'),
        name='renters-assured-shorthold-tenancies'),

    url(r'^renters/assured_tenancies$',
        TemplateView.as_view(template_name='website/renters/assured_tenancies.html'),
        name='renters-assured_tenancies'),

    url(r'^renters/can_council_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_council_tenants_stop_the_bailiffs.html'),
        name='renters-can_council_tenants_stop_the_bailiffs'),

    url(r'^renters/can_housing_association_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_housing_association_tenants_stop_the_bailiffs.html'),
        name='renters-can_housing_association_tenants_stop_the_bailiffs'),

    url(r'^renters/can_private_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_private_tenants_stop_the_bailiffs.html'),
        name='renters-can_private_tenants_stop_the_bailiffs'),

    url(r'^renters/complain_to_environmental_health_about_rented_housing$',
        TemplateView.as_view(template_name='website/renters/complain_to_environmental_health_about_rented_housing.html'),
        name='renters-complain_to_environmental_health_about_rented_housing'),

    url(r'^renters/complain_about_council_or_housing_association_repairs$',
        TemplateView.as_view(
            template_name='website/renters/complain_about_council_or_housing_association_repairs.html'),
        name='renters-complain_about_council_or_housing_association_repairs'),

    url(r'^renters/complain_to_the_ombudsman_about_repairs_in_social_housing$',
        TemplateView.as_view(
            template_name='website/renters/complain_to_the_ombudsman_about_repairs_in_social_housing.html'),
        name='renters-complain_to_the_ombudsman_about_repairs_in_social_housing'),

    url(r'^renters/damage_or_wear_and_tear$',
        TemplateView.as_view(
            template_name='website/renters/damage_or_wear_and_tear.html'),
        name='renters-damage_or_wear_and_tear'),

    url(r'^renters/damp_and_mould_in_rented_homes$',
        TemplateView.as_view(
            template_name='website/renters/damp_and_mould_in_rented_homes.html'),
        name='renters-damp_and_mould_in_rented_homes'),

    url(r'^renters/deposit-check$', TemplateView.as_view(template_name='website/renters/deposit-check.html'),
        name='renters-deposit-check'),

    url(r'^renters/deposit-check-lookup$',
        TemplateView.as_view(
            template_name='website/renters/deposit-check-lookup.html'),
        name='renters-deposit-check-lookup'),

    url(r'^renters/disrepair-advice$',
        TemplateView.as_view(template_name='website/renters/disrepair-advice.html'),
        name='renters-disrepair-advice'),

    url(r'^renters/doing_the_repairs_if_your_landlord_wont$',
        TemplateView.as_view(
            template_name='website/renters/doing_the_repairs_if_your_landlord_wont.html'),
        name='renters-doing_the_repairs_if_your_landlord_wont'),

    url(r'^renters/deposit-protection-claims$',
        TemplateView.as_view(template_name='website/renters/deposit-protection-claims.html'),
        name='deposit-protection-claims'),

    url(r'^renters/electrical_safety_in_rented_homes$',
        TemplateView.as_view(template_name='website/renters/electrical_safety_in_rented_homes.html'),
        name='renters-electrical_safety_in_rented_homes'),

    url(r'^renters/ending_a_periodic_tenancy$',
        TemplateView.as_view(template_name='website/renters/ending_a_periodic_tenancy.html'),
        name='renters-ending_a_periodic_tenancy'),

    url(r'^renters/energy_costs_in_shared_accommodation$',
        TemplateView.as_view(template_name='website/renters/energy_costs_in_shared_accommodation.html'),
        name='renters-energy_costs_in_shared_accommodation'),

    url(r'^renters/eviction$',
        TemplateView.as_view(template_name='website/renters/eviction.html'),
        name='renters-eviction'),

    url(r'^renters/eviction_documents_the_court_sends_you$',
        TemplateView.as_view(template_name='website/renters/eviction_documents_the_court_sends_you.html'),
        name='renters-eviction_documents_the_court_sends_you'),

    url(r'^renters/eviction_for_rent_arrears$',
        TemplateView.as_view(template_name='website/renters/eviction_for_rent_arrears.html'),
        name='renters-eviction_for_rent_arrears'),

    url(r'^renters/eviction-of-assured-shorthold-tenants$',
        TemplateView.as_view(template_name='website/renters/eviction-of-assured-shorthold-tenants.html'),
        name='renters-eviction-of-assured-shorthold-tenants'),

    url(r'^renters/eviction_of_assured_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_assured_tenants.html'),
        name='renters-eviction_of_assured_tenants'),

    url(r'^renters/eviction_of_lodgers_and_other_excluded_occupiers$',
        TemplateView.as_view(template_name='website/renters/eviction_of_lodgers_and_other_excluded_occupiers.html'),
        name='renters-eviction_of_lodgers_and_other_excluded_occupiers'),

    url(r'^renters/eviction_of_regulated_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_regulated_tenants.html'),
        name='renters-eviction_of_regulated_tenants'),

    url(r'^renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection$',
        TemplateView.as_view(template_name='website/renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection.html'),
        name='renters-eviction_of_students_in_halls_and_other_occupiers_with_basic_protection'),

    url(r'^renters/eviction_notices_from_private_landlords',
        TemplateView.as_view(template_name='website/renters/eviction_notices_from_private_landlords.html'),
        name='renters-eviction_notices_from_private_landlords'),

website/models.py
from django.db import models

# Create your models here.

# Test
class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()

    def __str__(self):
        return self.name
# End Test

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class NewsletterUserSignUpForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels=False

    class Meta:
        model = NewsletterUserSignUpFormfield = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email


# Test

# from invoices.models import Customer
class InvoiceForm(forms.Form):
    FORMAT_CHOICES = (
        ('pdf', 'PDF'),
        ('docx', 'MS Word'),
        ('html', 'HTML'),
    )
    number = forms.CharField(label='Invoice #')
    # customer = forms.ModelChoiceField(queryset=Customer.objects.all())
    subject = forms.CharField()
    amount = forms.DecimalField()
    format = forms.ChoiceField(choices=FORMAT_CHOICES)

# End Test

website/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from blog.models import Post
# from docx import *
from docx import Document
# from docx.shared import Inches
from django.http import HttpResponse
import datetime
from io import StringIO


class HomeView(TemplateView):
    template_name = 'website/home.html'


def home(request, template_name):
    return render(request, template_name)


def latest_post_footer(request):
    post = Post.objects.order_by('-published')[0:3]
    template = 'website/base.html'
    context = {'posts': post}
    return render(request, template, context)

# Test
from reportlab.pdfgen import canvas
from django.http import HttpResponse


def some_view(request):
    if request.GET.get('pdf'):
        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

        # Create the PDF object, using the response object as its "file."
        p = canvas.Canvas(response)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response

# End Test

'''
def test_document(request):

    document = Document()
    docx_title = "TEST_DOCUMENT.docx"
    # ---- Cover Letter ----
    # document.add_picture((r'%s/static/images/my-header.png' % (settings.PROJECT_PATH)), width=Inches(4))
    document.add_paragraph()
    document.add_paragraph("%s" % datetime.date.today().strftime('%d, %B, %Y'))

    document.add_paragraph('Dear Sir or Madam:')
    document.add_paragraph('We are pleased to help you with your widgets.')
    document.add_paragraph('Please feel free to contact me for any additional information.')
    document.add_paragraph('I look forward to assisting you in this project.')

    document.add_paragraph()
    document.add_paragraph('Best regards,')
    document.add_paragraph('Acme Specialist 1]')
    document.add_page_break()

    # Prepare document for download
    # -----------------------------
    f = StringIO()
    document.save(f)
    length = f.tell()
    f.seek(0)
    response = HttpResponse(
        f.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    response['Content-Disposition'] = 'attachment; filename=' + docx_title
    response['Content-Length'] = length
    return response'''

website/templates/website/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}About Represent{% endblock %}
{% block description %}About{% endblock %}
{% block author %}Represent{% endblock %}


{% block head %}
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-2">
        <h1>Welcome to Represent Law</h1>

        <p> We are here to helo you with all your legal needs.</p>

            </div>
    </div>
{% endblock %}

website/templates/website/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Contact represent{% endblock %}
{% block description %}Contact Represent{% endblock %}
{% block author %}Represent{% endblock %}

<h1>Home</h1>

{% block head %}
{% endblock %}

<h1 style="color:black" class="pagination-centered"></h1>
<p></p>


{% block content %}
<div class="container-fluid">
    <div class="col-md-6 offset-md-2">

            <div class="page-header">
                <h1>Contact Represent</h1>
            </div>
            <p>If you currently have a renting problem and would like to know how Represent can help you please contact us
            at <a href="mailto:contact@nralliance.co.uk"> contact@nralliance.co.uk</a> or by completing the form below.  We respond to you message as soon as possible.</p>


        <h1>Contact Represent</h1>
        </div>
</div>
{%  endblock %}

website/templates/website/home_temp.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Represent Renters{% endblock %}
{% block description %}Represent helping renters with deposits, deposit protection, HMOs, Rent Repayment Orders and Repairs{% endblock %}
{% block author %}Represent{% endblock %}

{% block head %}
    <link href="{% static 'website/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
    <link rel="icon" type="image/jpg" sizes="32x32" href="/website/img/represent_icon2.jpg">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
{% endblock %}

{% block body %}

<!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron" style="background-color:black">
            <div class="container">

              <div class="bs-docs-header">
                <h1 style="color:white" align="center">Represent Law </h1>
                <h1 align="center"><small style="color:white">Renters Services</small></h1>
            </div>

            </div>
          </div>


<div class="container">
        <div class="page-header" align="center">
            <h1>Practice Areas</h1>
        </div>


        <div class="row align-items-center">

            <div class="col-sm-6 col-md-4" style="margin-top:50px">
            <div class="thumbnail">
                <a href="{% url 'website:deposit-protection-claims' %}">
                    <img src="{% static 'img/pound_sign.jpg' %}" width="300" height="200" alt="Housing Disrepair Claims">
                </a>
              <div class="caption">
                  <a href="{% url 'website:deposit-protection-claims' %}"><h3 align="center" style="margin-top:20px">Tenancy Deposit Claims</h3></a>
                  <li align="left">Has your landlord failed to protect your deposit?</li>
                  <li align="left">Has your landlord taken money from your deposit?</li>
                  <li align="left">Has your landlord failed to issue the prescribed information</li>
                <p>You might be able to claim thousands in compensation.</p>
                <p><a href="{% url 'website:deposit-protection-claims' %}" class="btn btn-primary btn-lg" role="button">Get help now</a></p>
              </div>
            </div>
          </div>



          <div class="col-sm-6 col-md-4" style="margin-top:50px">
            <div class="thumbnail">
                <a href="{% url 'website:renters-disrepair-claims' %}">
                    <img src="{% static 'img/disrepair_cartoon.jpg' %}" width="300" height="200" alt="Housing Disrepair Claims">
                </a>
              <div class="caption">
                  <a href="{% url 'website:renters-disrepair-claims' %}"><h3 align="center" style="margin-top:20px">Disrepair Claims</h3></a>
                  <li align="left">Is your landlord not doing repairs?</li>
                  <li align="left">Have you complained and nothing has been done?</li>
                  <p>Your landlord has a legal duty to make necessary repairs.
                      If you're unhappy with your rented property
                      Contact us today to see if you can claim compensation</p>

                <p><a href="{% url 'website:renters-disrepair-claims' %}" class="btn btn-primary btn-lg" role="button">Get help now</a></p>
              </div>
            </div>
          </div>

            <!--HMO Claims-->
        <div class="col-sm-6 col-md-4" style="margin-top:50px">
            <div class="thumbnail">
                <a href="{% url 'website:renters-hmo-claims' %}">
                    <img src="{% static 'img/HMOlicensing.png' %}" width="300" height="200" alt="Rent Repayment Order">
                </a>
                 <a href="{% url 'website:renters-disrepair-claims' %}"><h3 align="center" style="margin-top:20px">Rent Repayment Orders</h3></a>
                <p>
                  <li align="left">Is your landlord renting out a property illegally?</li>
                    <li align="left">Is your landlord in breach of HMO regulations?</li>
                </p>
                  <p>If so you might be able to claim up to 12 months' rent back from your landlord. Contact
                  Represent today to see if we can help!</p>
                <p><a href="{% url 'website:renters-hmo-claims' %}" class="btn btn-primary btn-lg" role="button">Get help</a></p>
              </div>
            </div>
          </div>


          <!--<div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <img src="{% static 'img/disrepair_cartoon.jpg' %}" alt="Check My Landlord" width="200" height="200" >
              <div class="caption">
                  <a href="/housing-disrepair"><h3 align="center">Landlord Checker</h3></a>
                <p>Landlord Checker</p>
                <p><a href="/housing-disrepair" class="btn btn-primary btn-lg" role="button">Check my landlord</a></p>
              </div>
            </div>
          </div> -->
        </div>

<div class="jumbotron" style="background-color:black">
            <div class="container">

              <div class="bs-docs-header">
                <a href="{% url 'website:renters-faqs' %}">
                    <h1 style="color:white" align="center">Housing Advice</h1></a>

            </div>
            </div>
</div>

<div class="container">

        <div class="row align-items-center">

            <div class="col-sm-6 col-md-6" style="margin-top:50px">
            <div class="thumbnail">
              <div class="caption">
                  <a href="{% url 'website:renters-private_renting' %}"><h3 align="center" style="margin-top:20px">
                      <i class="fa fa-home"><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>

              </i>
                      Private Renting</h3></a>
              </div>
            </div>
          </div>



          <div class="col-sm-6 col-md-6" style="margin-top:50px">
            <div class="thumbnail">

              <div class="caption">
                  <a href="{% url 'website:renters-tenancy-deposits' %}"><h3 align="center" style="margin-top:20px">
                      <i class="fa fa-gbp"><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>

              </i> Tenancy Deposits</h3></a>
              </div>
            </div>
          </div>


        <div class="col-sm-6 col-md-6" style="margin-top:50px">
            <div class="thumbnail">

                 <a href="{% url 'website:renters-disrepair-advice' %}"><h3 align="center" style="margin-top:20px">
                     <i class="fa fa-wrench"></i> Repairs</h3></a>
              </div>
            </div>

            <div class="col-sm-6 col-md-6" style="margin-top:50px">
            <div class="thumbnail">
                 <a href="{% url 'website:renters-eviction' %}"><h3 align="center" style="margin-top:20px">
                     <i class="fa fa-lock"><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>

              </i> Eviction</h3></a>
                <p>
              </div>
            </div>

          </div>
        </div>



     <div class="jumbotron" style="background-color:black">
            <div class="container">

              <div class="bs-docs-header">
                <a href="{% url 'website:renters-faqs' %}">
                    <h1 style="color:white" align="center">Check our our Renters FAQs </h1></a>

            </div>

            </div>
          </div>
<!--FAQs-->

<div class="container">
    <div class="col-md-6 offset-md-2">

            <h3><a title="Rent Deposit recovery" href="https://www.nationalrentersalliance.co.uk/deposit-recovery">
                  <i class="fa fa-gbp"><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>

              </i>  Deposit Recovery</a></h3>

                <p class="text-justify">Is your landlord or letting agent not returning your
                deposit? Was your deposit placed in a government-backed deposit guarantee scheme
                within 30 days of the start of your tenancy? </p>

        <p>Is your landlord or letting agent
                making false claims <span lang="en-gb">about</span> <em>professional cleaning </em>to unfairly
                <strong><span lang="en-gb">take</span> money from your deposit<span lang="en-gb">?</span></strong>
                <span lang="en-gb"></p>
         <p>nfortunately, this is becoming the norm rather than the
                exception. </span>The National Renters Alliance team has over twenty years
        <span lang="en-gb">'</span> experience helping renters recover their rightfully owed money.</p>
         <p> See our frequently asked questions for
        <a href="https://www.nationalrentersalliance.co.uk/frequently-asked-questions-english">
            <strong>common reasons landlords use to take money from your deposit.</strong></a></p>


                <div class="bs-callout bs-callout-primary">
                    <a href="/contact"><h4>Contact Represent</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation for your deposit.</p>
                    <p><a href="https://www.representlaw.com/contact" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>
    </div>


<!--Disrepair-->
    <div class="col-md-6 offset-md-2">

         <h3><a title="Repairs and Maintenance"
                href="https://www.nationalrentersalliance.co.uk/repairs-and-maintenance">
             <i class="fa fa-wrench"></i>  Repairs and Maintenance</a></h3>
                <p class="text-justify">If your landlord or letting agent is
                    <strong>not doing repairs they are responsible for?</strong>
                    Have you complained about repairs and nothing
                    is being done?</p>&nbsp;

                <p>If so contact Represent to see if we can help. </p>

                <p>If you are unsure about which
                    <a href="https://www.nationalrentersalliance.co.uk/frequently-asked-questions-english">
                    housing repairs you are responsible for please visit our frequently asked
                    questions.</a>&nbsp;

                    <p>Many landlords and letting agents use renter's lack of
                    knowledge of their rights to give them a raw deal. </p>

                <div class="bs-callout bs-callout-primary">
                    <a href="https://www.representlaw.com/contact"><h4>Contact Represent</h4></a>
                    <p></p>
                    <p>Get in touch with Represent to see if you can claim compensation for disrepair.</p>
                    <p><a href="https://www.representlaw.com/contact" class="btn btn-primary btn-lg" role="button">Contact Represent</a></p>

                </div>
    </div>
</div>

{% endblock %}

website/templates/website/test.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block title %}Add comment to {{ category.name }}{% endblock %}
{% block description %}{{ post.seo_title }}{% endblock %}
{% block author %}Represent{% endblock %}

{% block content %}

<div class="container">
        <div class ="col-md-8">
            <div class="page-header">
                <h1>Sign up to the Represent newsletter</h1>
            </div>
                <form method='POST'>
                    {% csrf_token %}
                    {% crispy form %}
                    <button type='submit' class="btn btn-success">Subscribe</button>
                    <p></p>
                </form>
        </div>
    </div>
{%  endblock %}