blog/urls.py
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .feeds import RSSSiteNewsFeed, AtomSiteNewsFeed


app_name = "blog"

urlpatterns = [
    url(r'^$', views.list_of_post, name='list_of_post'),
    # url(r'^$', TemplateView.as_view(template_name='blog/list_of_post.html'), name='list_of_post'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name='list_of_post_by_category'),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^rss/feed/$', RSSSiteNewsFeed()),
    url(r'^sitenews/atom/$', AtomSiteNewsFeed()),
]

# TODO haystack search

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

representlaw/urls.py
# from django.urls import include, path
from representlaw import views as representlaw_views


from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [

    url(r'^', include('website.urls', namespace='website')),
    url(r'^admin/', admin.site.urls),
    url(r'^myaccount/', include('myaccount.urls', namespace='myaccount')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^contact/$', ContactView.as_view(), name='envelope-contact'),
    # url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^website/', include('website.urls', namespace='website')),
]

website/urls.py
from django.conf.urls import url, include
from website.views import HomeView
from django.views.generic import TemplateView

app_name = "website"

urlpatterns = [
    # url(r'^$', HomeView.as_view(), name='home'),
    url(r'^$', TemplateView.as_view(template_name='website/home_temp.html'), name='home_temp'),
    url(r'^about/$', TemplateView.as_view(template_name='website/about.html'), name='about'),
    url(r'^terms-and-conditions/$', TemplateView.as_view(template_name='website/terms-and-conditions.html'),
        name='terms_and_conditions'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='website/privacy-policy.html'), name='privacy-policy'),

    # url(r'^contact/$', TemplateView.as_view(template_name='website/contact.html'), name='contact'),

    # url(r'^contact/', include('contact_form.urls'), name='contact_form'),
    # url(r'^contact/',    include('envelope.urls'), name='contact_form'),

    url(r'^cookie-policy/$', TemplateView.as_view(template_name='website/cookie-policy.html'),
        name='cookie-policy'),

    # Conveyancing Commercial
    url(r'^conveyancing-commercial/$',
        TemplateView.as_view(template_name='website/conveyancing-commercial/conveyancing-commercial-home.html'),
        name='conveyancing-commercial-home'),

    # Conveyancing Residential
    url(r'^conveyancing-residential/$',
        TemplateView.as_view(template_name='website/conveyancing-residential/conveyancing-residential-home.html'),
        name='conveyancing-residential-home'),

    # Elderly Client
    url(r'^elderly-client-services/$',
        TemplateView.as_view(template_name='website/elderly-client/elderly-client-home.html'),
        name='elderly-client-home'),

    # Employment
    url(r'^employment-and-tribunals/$',
        TemplateView.as_view(template_name='website/employment/employment-home.html'),
        name='employment-home'),

    # Family
    url(r'^family-and-children/$',
        TemplateView.as_view(template_name='website/family-and-children/family-home.html'),
        name='family-home'),


    # Leasehold
    url(r'^leasehold/$', TemplateView.as_view(template_name='website/leasehold/testing.html'), name='leasehold-home'),

    url(r'^leasehold/what_is_leasehold$',
        TemplateView.as_view(template_name='website/leasehold/what_is_leasehold.html'),
        name='leasehold-what_is_leasehold'),

    # Litigation
    url(r'^litigation-and-disputes/$',
        TemplateView.as_view(template_name='website/litigation-and-disputes/litigation-home.html'),
        name='litigation-home'),

    # Power Attorney
    url(r'^power-attorney-court-protection/$',
        TemplateView.as_view(template_name='website/power-attorney-court-protection/power-attorney-court-protection.html'),
        name='power-attorney-home'),

    # Probate and Estate services
    url(r'^probate-and-estates/$', TemplateView.as_view(template_name='website/probate-and-estates/probate-home.html'),
        name='probate-home'),


    # Renters
    url(r'^renting/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renting-home'),
    url(r'^renting/faqs$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'),
        name='renting-faqs-english'),

    # Will writing services
    url(r'^wills/$', TemplateView.as_view(template_name='website/wills/will-writing.html'), name='wills'),
    url(r'^wills-trusts/$', TemplateView.as_view(template_name='website/wills/wills-trusts.html'), name='wills-trusts'),
    url(r'^wills/make-my-will$', TemplateView.as_view(template_name='website/wills/make-my-will.html'),
        name='make-my-will'),


    # Renting
    url(r'^renters/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renters-home'),
    url(r'^renters/renting-faqs/$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'), name='renters-faqs'),


    # Renting/deposits

    url(r'^renters/assured-shorthold-tenancies$',
        TemplateView.as_view(template_name='website/renters/assured-shorthold-tenancies.html'),
        name='renters-assured-shorthold-tenancies'),

    url(r'^renters/assured_tenancies$',
        TemplateView.as_view(template_name='website/renters/assured_tenancies.html'),
        name='renters-assured_tenancies'),

    url(r'^renters/can_council_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_council_tenants_stop_the_bailiffs.html'),
        name='renters-can_council_tenants_stop_the_bailiffs'),

    url(r'^renters/can_housing_association_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_housing_association_tenants_stop_the_bailiffs.html'),
        name='renters-can_housing_association_tenants_stop_the_bailiffs'),

    url(r'^renters/can_private_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_private_tenants_stop_the_bailiffs.html'),
        name='renters-can_private_tenants_stop_the_bailiffs'),

    url(r'^renters/complain_to_environmental_health_about_rented_housing$',
        TemplateView.as_view(template_name='website/renters/complain_to_environmental_health_about_rented_housing.html'),
        name='renters-complain_to_environmental_health_about_rented_housing'),

    url(r'^renters/complain_about_council_or_housing_association_repairs$',
        TemplateView.as_view(
            template_name='website/renters/complain_about_council_or_housing_association_repairs.html'),
        name='renters-complain_about_council_or_housing_association_repairs'),

    url(r'^renters/complain_to_the_ombudsman_about_repairs_in_social_housing$',
        TemplateView.as_view(
            template_name='website/renters/complain_to_the_ombudsman_about_repairs_in_social_housing.html'),
        name='renters-complain_to_the_ombudsman_about_repairs_in_social_housing'),

    url(r'^renters/damage_or_wear_and_tear$',
        TemplateView.as_view(
            template_name='website/renters/damage_or_wear_and_tear.html'),
        name='renters-damage_or_wear_and_tear'),

    url(r'^renters/damp_and_mould_in_rented_homes$',
        TemplateView.as_view(
            template_name='website/renters/damp_and_mould_in_rented_homes.html'),
        name='renters-damp_and_mould_in_rented_homes'),

    url(r'^renters/deposit-check$', TemplateView.as_view(template_name='website/renters/deposit-check.html'),
        name='renters-deposit-check'),

    url(r'^renters/deposit-check-lookup$',
        TemplateView.as_view(
            template_name='website/renters/deposit-check-lookup.html'),
        name='renters-deposit-check-lookup'),

    url(r'^renters/disrepair-advice$',
        TemplateView.as_view(template_name='website/renters/disrepair-advice.html'),
        name='renters-disrepair-advice'),

    url(r'^renters/doing_the_repairs_if_your_landlord_wont$',
        TemplateView.as_view(
            template_name='website/renters/doing_the_repairs_if_your_landlord_wont.html'),
        name='renters-doing_the_repairs_if_your_landlord_wont'),

    url(r'^renters/deposit-protection-claims$',
        TemplateView.as_view(template_name='website/renters/deposit-protection-claims.html'),
        name='deposit-protection-claims'),

    url(r'^renters/electrical_safety_in_rented_homes$',
        TemplateView.as_view(template_name='website/renters/electrical_safety_in_rented_homes.html'),
        name='renters-electrical_safety_in_rented_homes'),

    url(r'^renters/ending_a_periodic_tenancy$',
        TemplateView.as_view(template_name='website/renters/ending_a_periodic_tenancy.html'),
        name='renters-ending_a_periodic_tenancy'),

    url(r'^renters/energy_costs_in_shared_accommodation$',
        TemplateView.as_view(template_name='website/renters/energy_costs_in_shared_accommodation.html'),
        name='renters-energy_costs_in_shared_accommodation'),

    url(r'^renters/eviction$',
        TemplateView.as_view(template_name='website/renters/eviction.html'),
        name='renters-eviction'),

    url(r'^renters/eviction_documents_the_court_sends_you$',
        TemplateView.as_view(template_name='website/renters/eviction_documents_the_court_sends_you.html'),
        name='renters-eviction_documents_the_court_sends_you'),

    url(r'^renters/eviction_for_rent_arrears$',
        TemplateView.as_view(template_name='website/renters/eviction_for_rent_arrears.html'),
        name='renters-eviction_for_rent_arrears'),

    url(r'^renters/eviction-of-assured-shorthold-tenants$',
        TemplateView.as_view(template_name='website/renters/eviction-of-assured-shorthold-tenants.html'),
        name='renters-eviction-of-assured-shorthold-tenants'),

    url(r'^renters/eviction_of_assured_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_assured_tenants.html'),
        name='renters-eviction_of_assured_tenants'),

    url(r'^renters/eviction_of_lodgers_and_other_excluded_occupiers$',
        TemplateView.as_view(template_name='website/renters/eviction_of_lodgers_and_other_excluded_occupiers.html'),
        name='renters-eviction_of_lodgers_and_other_excluded_occupiers'),

    url(r'^renters/eviction_of_regulated_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_regulated_tenants.html'),
        name='renters-eviction_of_regulated_tenants'),

    url(r'^renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection$',
        TemplateView.as_view(template_name='website/renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection.html'),
        name='renters-eviction_of_students_in_halls_and_other_occupiers_with_basic_protection'),

    url(r'^renters/eviction_notices_from_private_landlords',
        TemplateView.as_view(template_name='website/renters/eviction_notices_from_private_landlords.html'),
        name='renters-eviction_notices_from_private_landlords'),

website/models.py
from django.db import models

# Create your models here.

# Test
class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()

    def __str__(self):
        return self.name
# End Test

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class NewsletterUserSignUpForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels=False

    class Meta:
        model = NewsletterUserSignUpFormfield = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email


# Test

# from invoices.models import Customer
class InvoiceForm(forms.Form):
    FORMAT_CHOICES = (
        ('pdf', 'PDF'),
        ('docx', 'MS Word'),
        ('html', 'HTML'),
    )
    number = forms.CharField(label='Invoice #')
    # customer = forms.ModelChoiceField(queryset=Customer.objects.all())
    subject = forms.CharField()
    amount = forms.DecimalField()
    format = forms.ChoiceField(choices=FORMAT_CHOICES)

# End Test

website/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from blog.models import Post
# from docx import *
from docx import Document
# from docx.shared import Inches
from django.http import HttpResponse
import datetime
from io import StringIO


class HomeView(TemplateView):
    template_name = 'website/home.html'


def home(request, template_name):
    return render(request, template_name)


def latest_post_footer(request):
    post = Post.objects.order_by('-published')[0:3]
    template = 'website/base.html'
    context = {'posts': post}
    return render(request, template, context)

# Test
from reportlab.pdfgen import canvas
from django.http import HttpResponse


def some_view(request):
    if request.GET.get('pdf'):
        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

        # Create the PDF object, using the response object as its "file."
        p = canvas.Canvas(response)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response

# End Test

'''
def test_document(request):

    document = Document()
    docx_title = "TEST_DOCUMENT.docx"
    # ---- Cover Letter ----
    # document.add_picture((r'%s/static/images/my-header.png' % (settings.PROJECT_PATH)), width=Inches(4))
    document.add_paragraph()
    document.add_paragraph("%s" % datetime.date.today().strftime('%d, %B, %Y'))

    document.add_paragraph('Dear Sir or Madam:')
    document.add_paragraph('We are pleased to help you with your widgets.')
    document.add_paragraph('Please feel free to contact me for any additional information.')
    document.add_paragraph('I look forward to assisting you in this project.')

    document.add_paragraph()
    document.add_paragraph('Best regards,')
    document.add_paragraph('Acme Specialist 1]')
    document.add_page_break()

    # Prepare document for download
    # -----------------------------
    f = StringIO()
    document.save(f)
    length = f.tell()
    f.seek(0)
    response = HttpResponse(
        f.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    response['Content-Disposition'] = 'attachment; filename=' + docx_title
    response['Content-Length'] = length
    return response'''

website/templates/website/wills/make-my-will.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Represent Wills{% endblock %}
{% block description %}Represent Wills{% endblock %}
{% block author %}Represent{% endblock %}


{% block head %}
{% endblock %}

{% block body %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Home</a></li>
  <li><a href="{% url 'website:wills' %}">Wills</a></li>
  <li class="active">Write my will</li>
</ol>

<div class="container">
        <div class="page-header" align="center">
            <h1>Make my will <small><br>Representing you and your loved ones, today and tomorrow</small></h1>
        </div>


    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-2">
        <h1>Welcome to Represent Law</h1>

        <h2>About the National Renters Alliance</h2>
        <p> The National Renters Alliance was established to help renters with tenancy problems caused by unscrupulous
          landlords and letting agents. This includes help recovering money unfairly taken from deposits, negotiating
          with landlords about housing repairs and other common renting problems.
        </p>

      <p>With the intensification of the housing crisis which is decades in the making, more and more people are
        forced to rent rather than buy their own homes. This situation is set to get worse as new house building has
        massively failed to keep pace with increases in the UK's population and the movement of young people to large
        cities. The expansion of buy-to-let landlords and rampant property speculation has pushed house prices beyond
        the reach of most people under the age of thirty-five. This situation is increasingly being exploited by bad
        landlords and letting agents who often invent spurious reasons to take money from deposits or avoid their
        repairing responsibilities.
      </p>

      <p> The National Renters Alliance is here to help you, whether it be getting your deposit back if it was unfairly
        taken from you, to forcing landlords and letting agents to do repairs which they are eligible for which you pay
        them to do through your rent. If you are renting, join us today and see how the National Renters Alliance can
        help you to take the stress out of renting.
      </p>
            </div>
    </div>
</div>
{% endblock %}

website/templates/website/wills/will-writing.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Represent Wills{% endblock %}
{% block description %}Represent Wills{% endblock %}
{% block author %}Represent{% endblock %}



{% block head %}
{% endblock %}

{% block body %}
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li class="active"><a href="{% url 'website:wills' %}">Wills</a></li>
</ol>

<div class="container">
        <div class="page-header" align="center">
            <a href="{% url 'website:make-my-will' %}"><h1>Represent Wills <small><br>Representing you and your loved ones, today and tomorrow</small></h1></a>
        </div>


    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-2">
        <h1>Welcome to Represent Law</h1>

        <h2>About the National Renters Alliance</h2>
        <p> The National Renters Alliance was established to help renters with tenancy problems caused by unscrupulous
          landlords and letting agents. This includes help recovering money unfairly taken from deposits, negotiating
          with landlords about housing repairs and other common renting problems.
        </p>

      <p>With the intensification of the housing crisis which is decades in the making, more and more people are
        forced to rent rather than buy their own homes. This situation is set to get worse as new house building has
        massively failed to keep pace with increases in the UK's population and the movement of young people to large
        cities. The expansion of buy-to-let landlords and rampant property speculation has pushed house prices beyond
        the reach of most people under the age of thirty-five. This situation is increasingly being exploited by bad
        landlords and letting agents who often invent spurious reasons to take money from deposits or avoid their
        repairing responsibilities.
      </p>

      <p> The National Renters Alliance is here to help you, whether it be getting your deposit back if it was unfairly
        taken from you, to forcing landlords and letting agents to do repairs which they are eligible for which you pay
        them to do through your rent. If you are renting, join us today and see how the National Renters Alliance can
        help you to take the stress out of renting.
      </p>
            </div>
    </div>
</div>
{% endblock %}

website/templates/website/wills/wills-trusts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Probates and Estates{% endblock %}
{% block description %}Represent Law Probate and Estates services{% endblock %}
{% block author %}Represent{% endblock %}

{% block head %}
    <link href="{% static 'website/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
    <link rel="icon" type="image/jpg" sizes="32x32" href="/website/img/represent_icon2.jpg">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
{% endblock %}

{% block body %}

<!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron" style="background-color:black">
            <div class="container">

             <div class="bs-docs-header">
                <h1 style="color:white" align="center">Represent Wills & Trusts </h1>
                <h1 align="center"><small style="color:white">Helping you today and tomorrow</small></h1>
            </div>
            </div>
        </div>

<div class="container-fluid">
    <div class="col-md-6 offset-md-2">

        <div class="page-header">
            <h1 align="center">Wills and Trusts</h1>
        </div>


           <p>A valid and properly drafted and executed Will should work for you to ensure your instructions about what
                you want to happen to your assets when you die. Represent can help you put in place this important
                document to take care of your property, personal possessions, money or other assets and if relevant also
                appoint guardians for young children and detail funeral arrangements.</p>

            <p>If you die without making a valid will, the law will determine how your property is distributed, in
                proportions set by statute (Government made laws). Without a valid will, you will have no say in how
                your estate is distributed among your family and friends. Therefore taking the time to put in place a
                valid will can avoid costly and stressful legal actions after your death since it gives you more control
                over the destination of your property than dying without a will.</p>

            <h1>Reviewing your will</h1>

            <p>Wills should be reviewed when you marry or enter into a civil partnership, cohabit, divorce or separate,
                move home or lose someone who was mentioned in a previous Will or if there are any other significant
                changes to your life. If you marry, any will made before marriage is automatically revoked (unless it
                was made in contemplation of that marriage).</p>

            <p>The team at Austin Ray has the breadth and depth of expertise to advise on any of these life events.</p>

            <h1>Expert Wills &amp; Trusts support from Represent</h1>

            <p>Although you choose what to say in your will, the law specifies how you should say it. If your will is
                not properly drafted and executed there is a risk that your will – or parts of it – may be considered
                invalid.</p>

            <p>At the time you give consideration to your will you may also want to consider making a Lasting Power of
                Attorney or applying for voluntary registration of your land at HM Land Registry. Indeed, how you hold
                any jointly-owned property is an important issue which our Represent team can guide you on; if required
                we can take care of severing a joint tenancy and other land related issues.</p>

            <p>At Represent we can help you by listening to what you want and what matters concern you about planning
                your will. Our expert team will ensure that any property related matters are also considered and dealt
                with appropriately. We will then draft a will or codicil for you, ensuring that all is executed
                correctly. In that way, you can be assured that you have an effective will dealing with your estate in
                the way you want, and that your loved ones will receive what they deserve.</p>

            <p>You may be interested to read the information on our website about <a
                        href="{% url 'website:power-attorney-home' %}">Powers of Attorney
                    & Court of Protection</a>, <a
                        href="{% url 'website:probate-home' %}">Administration of
                    Estates/Probate</a> and <a href="{% url 'website:elderly-client-home' %}">Elderly
                    Client Services</a>.</p>
        </div>
</div>

{% endblock %}