blog/urls.py
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .feeds import RSSSiteNewsFeed, AtomSiteNewsFeed


app_name = "blog"

urlpatterns = [
    url(r'^$', views.list_of_post, name='list_of_post'),
    # url(r'^$', TemplateView.as_view(template_name='blog/list_of_post.html'), name='list_of_post'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name='list_of_post_by_category'),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^rss/feed/$', RSSSiteNewsFeed()),
    url(r'^sitenews/atom/$', AtomSiteNewsFeed()),
]

# TODO haystack search

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myaccount/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

app_name = "myaccount"

urlpatterns = [
    # url(r'^$', views.home),
    url(r'^login/$', login, {'template_name': 'myaccount/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'myaccount/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password$', views.change_password, name='change_password'),
    url(r'^reset-password$', password_reset, {'template_name': 'myaccount/reset_password.html'},
        name='reset_password'),

    # url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'myaccount/password_reset_done.html'},
        name='password_reset_done'),


    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'myaccount/password_reset_complete.html'}, name='password_reset_complete')
]

representlaw/urls.py
# from django.urls import include, path
from representlaw import views as representlaw_views


from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [

    url(r'^', include('website.urls', namespace='website')),
    url(r'^admin/', admin.site.urls),
    url(r'^myaccount/', include('myaccount.urls', namespace='myaccount')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^contact/$', ContactView.as_view(), name='envelope-contact'),
    # url(r'^contact/', include('sendemail.urls', namespace='sendemail')),
    # url(r'^website/', include('website.urls', namespace='website')),
]

website/urls.py
from django.conf.urls import url, include
from website.views import HomeView
from django.views.generic import TemplateView

app_name = "website"

urlpatterns = [
    # url(r'^$', HomeView.as_view(), name='home'),
    url(r'^$', TemplateView.as_view(template_name='website/home_temp.html'), name='home_temp'),
    url(r'^about/$', TemplateView.as_view(template_name='website/about.html'), name='about'),
    url(r'^terms-and-conditions/$', TemplateView.as_view(template_name='website/terms-and-conditions.html'),
        name='terms_and_conditions'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='website/privacy-policy.html'), name='privacy-policy'),

    # url(r'^contact/$', TemplateView.as_view(template_name='website/contact.html'), name='contact'),

    # url(r'^contact/', include('contact_form.urls'), name='contact_form'),
    # url(r'^contact/',    include('envelope.urls'), name='contact_form'),

    url(r'^cookie-policy/$', TemplateView.as_view(template_name='website/cookie-policy.html'),
        name='cookie-policy'),

    # Conveyancing Commercial
    url(r'^conveyancing-commercial/$',
        TemplateView.as_view(template_name='website/conveyancing-commercial/conveyancing-commercial-home.html'),
        name='conveyancing-commercial-home'),

    # Conveyancing Residential
    url(r'^conveyancing-residential/$',
        TemplateView.as_view(template_name='website/conveyancing-residential/conveyancing-residential-home.html'),
        name='conveyancing-residential-home'),

    # Elderly Client
    url(r'^elderly-client-services/$',
        TemplateView.as_view(template_name='website/elderly-client/elderly-client-home.html'),
        name='elderly-client-home'),

    # Employment
    url(r'^employment-and-tribunals/$',
        TemplateView.as_view(template_name='website/employment/employment-home.html'),
        name='employment-home'),

    # Family
    url(r'^family-and-children/$',
        TemplateView.as_view(template_name='website/family-and-children/family-home.html'),
        name='family-home'),


    # Leasehold
    url(r'^leasehold/$', TemplateView.as_view(template_name='website/leasehold/testing.html'), name='leasehold-home'),

    url(r'^leasehold/what_is_leasehold$',
        TemplateView.as_view(template_name='website/leasehold/what_is_leasehold.html'),
        name='leasehold-what_is_leasehold'),

    # Litigation
    url(r'^litigation-and-disputes/$',
        TemplateView.as_view(template_name='website/litigation-and-disputes/litigation-home.html'),
        name='litigation-home'),

    # Power Attorney
    url(r'^power-attorney-court-protection/$',
        TemplateView.as_view(template_name='website/power-attorney-court-protection/power-attorney-court-protection.html'),
        name='power-attorney-home'),

    # Probate and Estate services
    url(r'^probate-and-estates/$', TemplateView.as_view(template_name='website/probate-and-estates/probate-home.html'),
        name='probate-home'),


    # Renters
    url(r'^renting/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renting-home'),
    url(r'^renting/faqs$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'),
        name='renting-faqs-english'),

    # Will writing services
    url(r'^wills/$', TemplateView.as_view(template_name='website/wills/will-writing.html'), name='wills'),
    url(r'^wills-trusts/$', TemplateView.as_view(template_name='website/wills/wills-trusts.html'), name='wills-trusts'),
    url(r'^wills/make-my-will$', TemplateView.as_view(template_name='website/wills/make-my-will.html'),
        name='make-my-will'),


    # Renting
    url(r'^renters/$', TemplateView.as_view(template_name='website/renters/renters-home.html'), name='renters-home'),
    url(r'^renters/renting-faqs/$', TemplateView.as_view(template_name='website/renters/renters-faqs.html'), name='renters-faqs'),


    # Renting/deposits

    url(r'^renters/assured-shorthold-tenancies$',
        TemplateView.as_view(template_name='website/renters/assured-shorthold-tenancies.html'),
        name='renters-assured-shorthold-tenancies'),

    url(r'^renters/assured_tenancies$',
        TemplateView.as_view(template_name='website/renters/assured_tenancies.html'),
        name='renters-assured_tenancies'),

    url(r'^renters/can_council_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_council_tenants_stop_the_bailiffs.html'),
        name='renters-can_council_tenants_stop_the_bailiffs'),

    url(r'^renters/can_housing_association_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_housing_association_tenants_stop_the_bailiffs.html'),
        name='renters-can_housing_association_tenants_stop_the_bailiffs'),

    url(r'^renters/can_private_tenants_stop_the_bailiffs$',
        TemplateView.as_view(template_name='website/renters/can_private_tenants_stop_the_bailiffs.html'),
        name='renters-can_private_tenants_stop_the_bailiffs'),

    url(r'^renters/complain_to_environmental_health_about_rented_housing$',
        TemplateView.as_view(template_name='website/renters/complain_to_environmental_health_about_rented_housing.html'),
        name='renters-complain_to_environmental_health_about_rented_housing'),

    url(r'^renters/complain_about_council_or_housing_association_repairs$',
        TemplateView.as_view(
            template_name='website/renters/complain_about_council_or_housing_association_repairs.html'),
        name='renters-complain_about_council_or_housing_association_repairs'),

    url(r'^renters/complain_to_the_ombudsman_about_repairs_in_social_housing$',
        TemplateView.as_view(
            template_name='website/renters/complain_to_the_ombudsman_about_repairs_in_social_housing.html'),
        name='renters-complain_to_the_ombudsman_about_repairs_in_social_housing'),

    url(r'^renters/damage_or_wear_and_tear$',
        TemplateView.as_view(
            template_name='website/renters/damage_or_wear_and_tear.html'),
        name='renters-damage_or_wear_and_tear'),

    url(r'^renters/damp_and_mould_in_rented_homes$',
        TemplateView.as_view(
            template_name='website/renters/damp_and_mould_in_rented_homes.html'),
        name='renters-damp_and_mould_in_rented_homes'),

    url(r'^renters/deposit-check$', TemplateView.as_view(template_name='website/renters/deposit-check.html'),
        name='renters-deposit-check'),

    url(r'^renters/deposit-check-lookup$',
        TemplateView.as_view(
            template_name='website/renters/deposit-check-lookup.html'),
        name='renters-deposit-check-lookup'),

    url(r'^renters/disrepair-advice$',
        TemplateView.as_view(template_name='website/renters/disrepair-advice.html'),
        name='renters-disrepair-advice'),

    url(r'^renters/doing_the_repairs_if_your_landlord_wont$',
        TemplateView.as_view(
            template_name='website/renters/doing_the_repairs_if_your_landlord_wont.html'),
        name='renters-doing_the_repairs_if_your_landlord_wont'),

    url(r'^renters/deposit-protection-claims$',
        TemplateView.as_view(template_name='website/renters/deposit-protection-claims.html'),
        name='deposit-protection-claims'),

    url(r'^renters/electrical_safety_in_rented_homes$',
        TemplateView.as_view(template_name='website/renters/electrical_safety_in_rented_homes.html'),
        name='renters-electrical_safety_in_rented_homes'),

    url(r'^renters/ending_a_periodic_tenancy$',
        TemplateView.as_view(template_name='website/renters/ending_a_periodic_tenancy.html'),
        name='renters-ending_a_periodic_tenancy'),

    url(r'^renters/energy_costs_in_shared_accommodation$',
        TemplateView.as_view(template_name='website/renters/energy_costs_in_shared_accommodation.html'),
        name='renters-energy_costs_in_shared_accommodation'),

    url(r'^renters/eviction$',
        TemplateView.as_view(template_name='website/renters/eviction.html'),
        name='renters-eviction'),

    url(r'^renters/eviction_documents_the_court_sends_you$',
        TemplateView.as_view(template_name='website/renters/eviction_documents_the_court_sends_you.html'),
        name='renters-eviction_documents_the_court_sends_you'),

    url(r'^renters/eviction_for_rent_arrears$',
        TemplateView.as_view(template_name='website/renters/eviction_for_rent_arrears.html'),
        name='renters-eviction_for_rent_arrears'),

    url(r'^renters/eviction-of-assured-shorthold-tenants$',
        TemplateView.as_view(template_name='website/renters/eviction-of-assured-shorthold-tenants.html'),
        name='renters-eviction-of-assured-shorthold-tenants'),

    url(r'^renters/eviction_of_assured_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_assured_tenants.html'),
        name='renters-eviction_of_assured_tenants'),

    url(r'^renters/eviction_of_lodgers_and_other_excluded_occupiers$',
        TemplateView.as_view(template_name='website/renters/eviction_of_lodgers_and_other_excluded_occupiers.html'),
        name='renters-eviction_of_lodgers_and_other_excluded_occupiers'),

    url(r'^renters/eviction_of_regulated_tenants$',
        TemplateView.as_view(template_name='website/renters/eviction_of_regulated_tenants.html'),
        name='renters-eviction_of_regulated_tenants'),

    url(r'^renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection$',
        TemplateView.as_view(template_name='website/renters/eviction_of_students_in_halls_and_other_occupiers_with_basic_protection.html'),
        name='renters-eviction_of_students_in_halls_and_other_occupiers_with_basic_protection'),

    url(r'^renters/eviction_notices_from_private_landlords',
        TemplateView.as_view(template_name='website/renters/eviction_notices_from_private_landlords.html'),
        name='renters-eviction_notices_from_private_landlords'),

website/models.py
from django.db import models

# Create your models here.

# Test
class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()

    def __str__(self):
        return self.name
# End Test

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class NewsletterUserSignUpForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels=False

    class Meta:
        model = NewsletterUserSignUpFormfield = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email


# Test

# from invoices.models import Customer
class InvoiceForm(forms.Form):
    FORMAT_CHOICES = (
        ('pdf', 'PDF'),
        ('docx', 'MS Word'),
        ('html', 'HTML'),
    )
    number = forms.CharField(label='Invoice #')
    # customer = forms.ModelChoiceField(queryset=Customer.objects.all())
    subject = forms.CharField()
    amount = forms.DecimalField()
    format = forms.ChoiceField(choices=FORMAT_CHOICES)

# End Test

website/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from blog.models import Post
# from docx import *
from docx import Document
# from docx.shared import Inches
from django.http import HttpResponse
import datetime
from io import StringIO


class HomeView(TemplateView):
    template_name = 'website/home.html'


def home(request, template_name):
    return render(request, template_name)


def latest_post_footer(request):
    post = Post.objects.order_by('-published')[0:3]
    template = 'website/base.html'
    context = {'posts': post}
    return render(request, template, context)

# Test
from reportlab.pdfgen import canvas
from django.http import HttpResponse


def some_view(request):
    if request.GET.get('pdf'):
        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

        # Create the PDF object, using the response object as its "file."
        p = canvas.Canvas(response)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response

# End Test

'''
def test_document(request):

    document = Document()
    docx_title = "TEST_DOCUMENT.docx"
    # ---- Cover Letter ----
    # document.add_picture((r'%s/static/images/my-header.png' % (settings.PROJECT_PATH)), width=Inches(4))
    document.add_paragraph()
    document.add_paragraph("%s" % datetime.date.today().strftime('%d, %B, %Y'))

    document.add_paragraph('Dear Sir or Madam:')
    document.add_paragraph('We are pleased to help you with your widgets.')
    document.add_paragraph('Please feel free to contact me for any additional information.')
    document.add_paragraph('I look forward to assisting you in this project.')

    document.add_paragraph()
    document.add_paragraph('Best regards,')
    document.add_paragraph('Acme Specialist 1]')
    document.add_page_break()

    # Prepare document for download
    # -----------------------------
    f = StringIO()
    document.save(f)
    length = f.tell()
    f.seek(0)
    response = HttpResponse(
        f.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    response['Content-Disposition'] = 'attachment; filename=' + docx_title
    response['Content-Length'] = length
    return response'''

website/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="{% block author %}{% endblock %}">
    <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />

    <!--TITLE-->
    <title>{% block title %}{% endblock %}</title>

    {% block css %}
    {% endblock %}

        {% block head %}
    {% endblock %}

    <!--CSS Files -->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/ie10-viewport-bug-workaround.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}" />-->

    <!--<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">



    <!--JS-->
    <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->
</head>

<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:about' %}">About <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:list_of_post' %}">Blog</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="/services" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Services
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!--<a class="dropdown-item" href="#">Family</a>
                            <a class="dropdown-item" href="#">Conveyancing</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Probate</a>-->

                            <a class="dropdown-item" href="{% url 'website:wills' %}">Wills</a>
                  <a class="dropdown-item" href="{% url 'website:probate-home' %}">Probate and Estates</a>
                  <a class="dropdown-item" href="{% url 'website:conveyancing-residential-home' %}">Buying a house</a>
                    <a class="dropdown-item" href="{% url 'website:conveyancing-residential-home' %}">Conveyancing (residential)</a>
                    <a class="dropdown-item" href="{% url 'website:conveyancing-commercial-home' %}">Commerical Conveyancing</a>
                    <a class="dropdown-item" href="{% url 'website:employment-home' %}">Employment law</a>
                  <a class="dropdown-item" href="{% url 'website:conveyancing-residential-home' %}">Selling a house</a>
                  <a class="dropdown-item" href="{% url 'website:leasehold-what_is_leasehold' %}">Extend my leasehold</a>
                  <a class="dropdown-item" href="{% url 'website:conveyancing-commercial-home' %}">Commercial law</a>
                  <a class="dropdown-item" href="{% url 'website:family-home' %}">Family law</a>
                  <a class="dropdown-item" href="{% url 'website:family-home' %}">Divorce</a>
                  <a class="dropdown-item" href="{% url 'website:power-attorney-home' %}">Lasting power of attorney</a>

                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'website:litigation-home' %}">Litigation</a>
                  <a class="dropdown-item" href="{% url 'website:litigation-home' %}">Debt recovery</a>
                  <a class="dropdown-item" href="{% url 'website:renting-home' %}">Landlord & Tenant Law</a>
                  <!--<li><a href="#">Immigration</a></li>-->
                   <div class="dropdown-divider"></div>

                            <a class="dropdown-item" href="/contact">Other</a>

                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact Us</a>
                    </li>

                    <!--TODO Add search functionality to form-->
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                </ul>



                {% if user.is_authenticated %}
                    <!-- TEST -->
                    <ul class="navbar-nav navbar-right">
                         <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:view_profile' %}">My Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:change_password' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:logout' %}">logout <span class="sr-only">(current)</span></a></li>
                    </ul>

                {% else %}
                        <ul class="navbar-nav navbar-right">
                            <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:login' %}">login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:reset_password' %}">Reset password</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'myaccount:register' %}">Register</a></li>
                        </ul>
                  {% endif %}

            </div>
        </nav>


    {% block body %}
    {% endblock %}

    {% block content %}
    {% endblock %}


<footer>
  <div class="container" style="margin-top: 20px">
    <div class="row">
      <div class="col-md-4 col-sm-6 footerleft ">
        <div class="logofooter">
            <img src="{% static 'images/represent_logo_sized.jpg' %}" alt="Represent Logo"/>
        </div>

          <p>Represent Law Limited VAT Reg. No.: 287518265 Registered in England and Wales, No. 10857999 <br>
          Regulated by the Solicitors Regulation Authority Registration No.SRA 641577
          </p>
        <p><i class="fa fa-map-pin"></i> 63 Sandbourne Avenue, Wimbledon, London, SW19 3EH</p>

          <p><i class="fa fa-phone"></i> {{ telephone }}</p>
          <p><i class="fa fa-envelope"></i>
              <a href="mailto: {{ represent_contact_email }}">{{ represent_contact_email }}</a></p>
      </div>
      <div class="col-md-2 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">GENERAL LINKS</h6>
        <ul class="footer-ul">
          <li><a href="#"> Careers</a></li>
          <li><a href="{% url 'website:privacy-policy' %}">Privacy Policy</a></li>
          <li><a href="{% url 'website:terms_and_conditions' %}">Terms & Conditions</a></li>
          <!--<li><a href="#"> Client Gateway</a></li>
          <li><a href="#"> Ranking</a></li>
          <li><a href="#"> Case Studies</a></li>
          <li><a href="#"> FAQs</a></li>-->
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">

        <h6 class="heading7">LATEST POSTS</h6>
          <div class="post">
              {% for post in posts %}
                <p><a href="{{post.get_absolute_url}}">{{ post.title }}</a><span>Posted on {{post.published}}</span></p>
              {% endfor %}
          </div>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <div class="col-sm-10 social-buttons">
            <h6 class="heading7">SOCIAL MEDIA</h6>
            <a href="https://www.facebook.com/NationalRentersAlliance/" class="btn btn-block btn-social btn-facebook">
              <i class="fa fa-facebook"></i> Visit us on Facebook
            </a>
            <a href="https://twitter.com/renter_alliance" class="btn btn-block btn-social btn-twitter">
              <i class="fa fa-twitter"></i> Visit us on Twitter
            </a>
            <a href="https://plus.google.com/114376859114257839374/about" class="btn btn-block btn-social btn-google-plus">
              <i class="fa fa-google-plus"></i> Visit us on Google+
            </a>
            <a href="https://www.linkedin.com/in/national-renters-alliance-6a6988120" class="btn btn-block btn-social btn-linkedin">
              <i class="fa fa-linkedin"></i> Visit us on Linkedin
            </a>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->

<div class="copyright">
  <div class="container">
    <div class="col-md-6" style="text-align:center">
      <p>Copyright © 2015 -  {% now "Y" %} National Renters Alliance Ltd. All rights
			reserved. </p>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>


        {% block js_files %}
        {% endblock %}

        <script>
            //OFF CANVAS MENU FUNCTION
            $(document).ready(function () {
              $('[data-toggle="offcanvas"]').click(function () {
                $('.row-offcanvas').toggleClass('active')
              });
            });
        </script>

</body>
</html>